CREATE DATABASE IF NOT EXISTS HealthForumDb
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE HealthForumDb;

CREATE TABLE IF NOT EXISTS ForumCategories (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Description VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS Topics (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(200) NOT NULL,
    Content TEXT NOT NULL,
    CategoryId INT NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
    CONSTRAINT FK_Topics_ForumCategories
        FOREIGN KEY (CategoryId) REFERENCES ForumCategories(Id)
);
